### ISSUE TITLE
Update pandoc-svelte-components

### ISSUE THREAD

**Issue by lduktus** [bmschmidt/bare-bones-blog#1]
The current version has a problem with the Blockquote component, which is already fixed.

See:
https://github.com/bmschmidt/pandoc-svelte-components/issues/7

**Comment by bmschmidt** [comment]
Thanks for the report. I've fixed it in this with https://github.com/bmschmidt/bare-bones-blog/commit/6d68376e70ea2fa56c41b00e09be003b497d08dc: leaving open to address two further issues.

- [ ] Update to use pandoc-svelte-components 0.3.2, not just 0.2.1, which could have other breaking changes on the demos
- [ ] Publish version 0.0.2 as released here to npm. (If this repo is even an npm package--I can't remember.)

**Comment by lduktus** [comment]
Thanks I tested it with version 0.3.2 and got an Error on build (0.2.1 works fine):

```
[commonjs--resolver] Missing "./Document.svelte" specifier in "pandoc-svelte-components" package
error during build:
Error: Missing "./Document.svelte" specifier in "pandoc-svelte-components" package
    at e (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:25)
    at n (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:627)
    at o (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:14845:1276)
    at resolveExports (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22032:20)
    at resolveDeepImport (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:22051:31)
    at tryNodeResolve (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21736:20)
    at Object.resolveId (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:21487:28)
    at Object.handler (file:///workspaces/sitv/node_modules/vite/dist/node/chunks/dep-3007b26d.js:44852:19)
    at file:///workspaces/sitv/node_modules/rollup/dist/es/shared/rollup.js:23891:40
    at async PluginDriver.hookFirstAndGetPlugin (file:///workspaces/sitv/node_modules/rollup/dist/es/shared/rollup.js:23791:28)
```

It is running on a Fedora 38 devcontainer and I haven't touched any of the other dependencies so far.
